### ISSUE TITLE
Unable to use AutoFill service

### ISSUE THREAD

**Issue by AE720** [nextcloud/passman-android#125]
Inside both the app and on my Nextcloud instance, they both work and are on the latest version but when I set Passman as an autofill service and make sure the vault is set in the settings (inside the app itself), I get the toast notification "No Active vault" when trying to use it.

There's a gear icon by passman when selecting it as Autofill but that instantly crashes. Here is the log I receive:

04-20 11:10:20.938 V/chatty  (4088): uid=10339(es.wolfi.app.passman) identical 26 lines
04-20 11:10:52.178 I/ActivityTaskManager(786): START u0 {act=android.intent.action.MAIN cmp=es.wolfi.app.passman/.PasswordList} from uid 1000
04-20 11:10:52.182 E/AndroidRuntime(3520): android.content.ActivityNotFoundException: Unable to find explicit activity class {es.wolfi.app.passman/es.wolfi.app.passman.PasswordList}; have you declared this activity in your AndroidManifest.xml?

Only thing of note is I'm using an apppassword

**Comment by rezeero25** [comment]
Using the passman app an Android 13 i got the same error using the gear icon in autofill:

android.content.AcitvityNotFoundException: Unable to find explicit activity class {es.wolfi.app.passman/es.wolfi.app.passman,PasswordList}

PasswordList was renamed to PasswordListActivity: c93d4401014a1a9805779718778a095ca43324f8
PasswordList is (still?) used in https://github.com/nextcloud/passman-android/blob/f257d1b9feb9c6a120be932914c47fdcc7c27b32/app/src/main/res/xml/autofill_service.xml#L2

Are these two variables related and should be changed (unified) accordingly?

**Comment by binsky08** [comment]
Interesting that I don't have that problem with the 1.4.0 on my test devices.
But nvm. yes, that should be changed to `android:settingsActivity="es.wolfi.app.passman.PasswordListActivity">`.
I'll try to make a bugfix release the next days

**Comment by rezeero25** [comment]
After update to 1.4.1 still error in Android settings to configure passman AS autofill service


```
type: crash
osVersion: google/sunfish/sunfish:13/TQ1A.230205.002/2023021000:user/release-keys
package: com.android.settings:33
process: com.android.settings
processUptime: 3370 + 329 ms

android.content.ActivityNotFoundException: Unable to find explicit activity class {es.wolfi.app.passman/es.wolfi.app.passman.PasswordListActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2208)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1845)
	at android.app.Activity.startActivityForResult(Activity.java:5518)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:689)
	at com.android.settings.core.SettingsBaseActivity.startActivityForResult(SettingsBaseActivity.java:157)
	at android.app.Activity.startActivityForResult(Activity.java:5437)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:670)
	at android.app.Activity.startActivity(Activity.java:5974)
	at android.app.Activity.startActivity(Activity.java:5941)
	at com.android.settings.applications.defaultapps.DefaultAppPreferenceController.startActivity(DefaultAppPreferenceController.java:100)
	at com.android.settings.applications.defaultapps.DefaultAppPreferenceController.lambda$mayUpdateGearIcon$0(DefaultAppPreferenceController.java:93)
	at com.android.settings.applications.defaultapps.DefaultAppPreferenceController.$r8$lambda$cVcZr407j6FGUYUMllpMiSbOHgo(Unknown Source:0)
	at com.android.settings.applications.defaultapps.DefaultAppPreferenceController$$ExternalSyntheticLambda0.onGearClick(Unknown Source:4)
	at com.android.settings.widget.GearPreference.onClick(GearPreference.java:84)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29341)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by binsky08** [comment]
It seems that a complete overhaul is needed there.
But this problem should not affect the autofill functionality.

@AE720 the "No Active vault" notification indicates, that there is no explicit autofill vault set in the app settings.
More information about that: https://github.com/nextcloud/passman-android/blob/master/FAQ.md#how-can-i-use-the-autofill-feature
